---
- name: Install Docker, CRI-Docker, and Kubernetes
  hosts: kube_master
  become: yes
  tasks:
    - name: Initialize Kubernetes Master Node
      shell: |
        kubeadm init --cri-socket unix:///var/run/cri-dockerd.sock --ignore-preflight-errors=all
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      register: kubeadm_output

    - name: Install Calico networking driver
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
      when: kubeadm_output is changed

    - name: Validate installed Kubernetes nodes
      shell: kubectl get nodes