---

- name: install jenkins
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Download Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz"
        dest: /opt/
    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.54.tar.gz
        dest: /opt/
        remote_src: yes
  
      - name: Download Jenkins WAR file
      get_url:
        url: https://get.jenkins.io/war-stable/latest/jenkins.war
        dest: /opt/apache-tomcat-9.0.54/webapps/jenkins.war

    - name: Ensure Tomcat service is enabled and started
      shell: /opt/apache-tomcat-9.0.54/bin/startup.sh
